Perlin noise
ob-algdatii-ss18/leistungsnachweis-dingo pull request #4
Opened 2018-04-18 21:26 UTC by orb1005

Please inform me if you find any mistakes

2018-04-20 10:57 UTC, Faaux requested changes
Bitte floats statt doubles benutzen da die Graka eh nicht genauer darstellen kann und es für uns keinen Einfluss hat. Gerade weil du die "Konstanten" mit 2.0f AKA als float angibst, d.h er wandelt sehr oft zwischen float und double hin und her.

Sonst super :)

2018-04-21 19:34 UTC, orb1005 commented
Vielen Dank für den Hinweis. Ich werd mich am Montag im Praktikum dran setzen.

2018-05-03 10:45 UTC, michaeleggers approved these changes

2018-05-04 20:34 UTC, Faaux approved these changes

2018-05-04 20:34 UTC, merged